#ifndef EMU_DEFS_H
#define EMU_DEFS_H

#define VIDEO_WIDTH 256
#define VIDEO_HEIGHT 192
#define DEFAULT_WINDOW_SCALE 3
#define DEFAULT_WINDOW_WIDTH (VIDEO_WIDTH * DEFAULT_WINDOW_SCALE)
#define DEFAULT_WINDOW_HEIGHT (VIDEO_HEIGHT * DEFAULT_WINDOW_SCALE)

#define MAIN_MEMORY_SIZE 65536
#define NUM_REGISTERS 16

#endif
